const data = {
    categories: [
      {
        id: 1,
        name: "Passport Services",
        image: "https://img.thecdn.in/278804/1699695734408_passportcategory.jpeg?width=384&format=webp",
        products: [
          {
            id: 1,
            name: "New Passport Application",
            description: "Effortlessly apply for your first passport.",
            price: 500,
            discountPrice: 450,
            image: "https://img.thecdn.in/278804/1699695734408_passportcategory.jpeg?width=384&format=webp",
          },
          {
            id: 2,
            name: "Passport Renewal",
            description: "Renew your expired passport quickly.",
            price: 300,
            discountPrice: 270,
            image: "https://img.thecdn.in/278804/1699695734408_passportcategory.jpeg?width=384&format=webp",
          },
          {
            id: 3,
            name: "Lost Passport Reissue",
            description: "Reissue your passport if it's lost or damaged.",
            price: 400,
            discountPrice: 360,
            image: "https://img.thecdn.in/278804/1699695734408_passportcategory.jpeg?width=384&format=webp",
          },
          {
            id: 4,
            name: "Tatkal Passport Service",
            description: "Get your passport processed on priority.",
            price: 1000,
            discountPrice: 900,
            image: "https://img.thecdn.in/278804/1699695734408_passportcategory.jpeg?width=384&format=webp",
          },
        ],
      },
      {
        id: 2,
        name: "RTO Services",
        image: "https://img.thecdn.in/278804/1699696985050_rtocategory.jpeg?width=384&format=webp",
        products: [
          {
            id: 5,
            name: "New Driving License",
            description: "Apply for a fresh driving license easily.",
            price: 200,
            discountPrice: 180,
            image: "https://img.thecdn.in/278804/1699696985050_rtocategory.jpeg?width=384&format=webp",
          },
          {
            id: 6,
            name: "License Renewal",
            description: "Renew your existing driving license.",
            price: 150,
            discountPrice: 135,
            image: "https://img.thecdn.in/278804/1699696985050_rtocategory.jpeg?width=384&format=webp",
          },
          {
            id: 7,
            name: "Vehicle Registration",
            description: "Get your vehicle registered hassle-free.",
            price: 300,
            discountPrice: 270,
            image: "https://img.thecdn.in/278804/1699696985050_rtocategory.jpeg?width=384&format=webp",
          },
          {
            id: 8,
            name: "Duplicate License",
            description: "Request a duplicate driving license.",
            price: 100,
            discountPrice: 90,
            image: "https://img.thecdn.in/278804/1699696985050_rtocategory.jpeg?width=384&format=webp",
          },
        ],
      },
      {
        id: 3,
        name: "Tehsil Services",
        image: "https://img.thecdn.in/278804/1699696876957_tahseelcategory.jpeg?width=384&format=webp",
        products: [
          {
            id: 9,
            name: "Land Record Update",
            description: "Update your land records at the tehsil office.",
            price: 100,
            discountPrice: 90,
            image: "https://img.thecdn.in/278804/1699696876957_tahseelcategory.jpeg?width=384&format=webp",
          },
          {
            id: 10,
            name: "Income Certificate",
            description: "Apply for an official income certificate.",
            price: 50,
            discountPrice: 45,
            image: "https://img.thecdn.in/278804/1699696876957_tahseelcategory.jpeg?width=384&format=webp",
          },
          {
            id: 11,
            name: "Caste Certificate",
            description: "Get your caste certificate issued.",
            price: 70,
            discountPrice: 65,
            image: "https://img.thecdn.in/278804/1699696876957_tahseelcategory.jpeg?width=384&format=webp",
          },
          {
            id: 12,
            name: "Property Valuation",
            description: "Estimate the value of your property.",
            price: 150,
            discountPrice: 135,
            image: "https://img.thecdn.in/278804/1699696876957_tahseelcategory.jpeg?width=384&format=webp",
          },
        ],
      },
      {
        id: 4,
        name: "Court Services",
        image: "https://img.thecdn.in/278804/1699696512744_courtcategory.jpeg?width=384&format=webp",
        products: [
          {
            id: 13,
            name: "Legal Advice",
            description: "Get expert legal advice for your issues.",
            price: 800,
            discountPrice: 750,
            image: "https://img.thecdn.in/278804/1699696512744_courtcategory.jpeg?width=384&format=webp",
          },
          {
            id: 14,
            name: "Document Drafting",
            description: "Draft legal documents professionally.",
            price: 500,
            discountPrice: 450,
            image: "https://img.thecdn.in/278804/1699696512744_courtcategory.jpeg?width=384&format=webp",
          },
          {
            id: 15,
            name: "Will Creation",
            description: "Create a legally binding will.",
            price: 600,
            discountPrice: 550,
            image: "https://img.thecdn.in/278804/1699696512744_courtcategory.jpeg?width=384&format=webp",
          },
          {
            id: 16,
            name: "Power of Attorney",
            description: "Get a registered power of attorney.",
            price: 400,
            discountPrice: 360,
            image: "https://img.thecdn.in/278804/1699696512744_courtcategory.jpeg?width=384&format=webp",
          },
        ],
      },
      {
        id: 5,
        name: "Choice Center Services",
        image: "https://img.thecdn.in/278804/1699696089515_choicecentercategory.jpeg?width=384&format=webp",
        products: [
          {
            id: 17,
            name: "Aadhaar Update",
            description: "Update your Aadhaar details seamlessly.",
            price: 50,
            discountPrice: 40,
            image: "https://img.thecdn.in/278804/1699696089515_choicecentercategory.jpeg?width=384&format=webp",
          },
          {
            id: 18,
            name: "PAN Card Application",
            description: "Apply for a new PAN card.",
            price: 100,
            discountPrice: 90,
            image: "https://img.thecdn.in/278804/1699696089515_choicecentercategory.jpeg?width=384&format=webp",
          },
          {
            id: 19,
            name: "Voter ID Registration",
            description: "Register for a new voter ID card.",
            price: 30,
            discountPrice: 25,
            image: "https://img.thecdn.in/278804/1699696089515_choicecentercategory.jpeg?width=384&format=webp",
          },
          {
            id: 20,
            name: "Document Scanning",
            description: "Professional scanning of important documents.",
            price: 20,
            discountPrice: 15,
            image: "https://img.thecdn.in/278804/1699696089515_choicecentercategory.jpeg?width=384&format=webp",
          },
        ],
      },
      {
        id: 6,
        name: "Chartered Accountant Services",
        image: "https://img.thecdn.in/278804/1699697234410_CAcategory.jpeg?width=384&format=webp",
        products: [
          {
            id: 21,
            name: "Income Tax Filing",
            description: "Expert assistance for filing income tax.",
            price: 500,
            discountPrice: 450,
            image: "https://img.thecdn.in/278804/1699697234410_CAcategory.jpeg?width=384&format=webp",
          },
          {
            id: 22,
            name: "GST Registration",
            description: "Simplified GST registration service.",
            price: 300,
            discountPrice: 270,
            image: "https://img.thecdn.in/278804/1699697234410_CAcategory.jpeg?width=384&format=webp",
          },
          {
            id: 23,
            name: "Audit Services",
            description: "Comprehensive auditing for businesses.",
            price: 1000,
            discountPrice: 950,
            image: "https://img.thecdn.in/278804/1699697234410_CAcategory.jpeg?width=384&format=webp",
          },
          {
            id: 24,
            name: "Business Registration",
            description: "Register your business hassle-free.",
            price: 700,
            discountPrice: 650,
            image: "https://img.thecdn.in/278804/1699697234410_CAcategory.jpeg?width=384&format=webp",
          },
        ],
      },
      {
        id: 7,
        name: "LPG Gas Services",
        image: "https://img.thecdn.in/278804/1699697873346_LPGgascategory.jpeg?width=384&format=webp",
        products: [
          {
            id: 25,
            name: "New LPG Connection",
            description: "Hassle-free LPG connection service.",
            price: 1000,
            discountPrice: 950,
            image: "https://img.thecdn.in/278804/1699697873346_LPGgascategory.jpeg?width=384&format=webp",
          },
          {
            id: 26,
            name: "Cylinder Refill",
            description: "Order an LPG cylinder refill easily.",
            price: 800,
            discountPrice: 750,
            image: "https://img.thecdn.in/278804/1699697873346_LPGgascategory.jpeg?width=384&format=webp",
          },
          {
            id: 27,
            name: "Gas Stove Repair",
            description: "Repair your gas stove quickly.",
            price: 300,
            discountPrice: 250,
            image: "https://img.thecdn.in/278804/1699697873346_LPGgascategory.jpeg?width=384&format=webp",
          },
          {
            id: 28,
            name: "LPG Safety Inspection",
            description: "Ensure safety with our LPG inspection service.",
            price: 150,
            discountPrice: 120,
            image: "https://img.thecdn.in/278804/1699697873346_LPGgascategory.jpeg?width=384&format=webp",
          },
        ],
      },
      {
        id: 8,
        name: "Insurance Services",
        image: "https://img.thecdn.in/278804/1699697905528_isurancecategory.jpeg?width=384&format=webp",
        products: [
          {
            id: 29,
            name: "Health Insurance",
            description: "Comprehensive health insurance plans.",
            price: 2000,
            discountPrice: 1800,
            image: "https://img.thecdn.in/278804/1699697905528_isurancecategory.jpeg?width=384&format=webp",
          },
          {
            id: 30,
            name: "Vehicle Insurance",
            description: "Insurance plans for cars and bikes.",
            price: 1500,
            discountPrice: 1350,
            image: "https://img.thecdn.in/278804/1699697905528_isurancecategory.jpeg?width=384&format=webp",
          },
          {
            id: 31,
            name: "Travel Insurance",
            description: "Secure your trips with travel insurance.",
            price: 1000,
            discountPrice: 850,
            image: "https://img.thecdn.in/278804/1699697905528_isurancecategory.jpeg?width=384&format=webp",
          },
          {
            id: 32,
            name: "Life Insurance",
            description: "Ensure your family's future with life insurance.",
            price: 5000,
            discountPrice: 4500,
            image: "https://img.thecdn.in/278804/1699697905528_isurancecategory.jpeg?width=384&format=webp",
          },
        ],
      },
    ],
  };
  
  export default data;
  