
import { CartProvider } from "./(pages)/cartContext/page";
import Footer from "./components/Footer";
import Header from "./components/Header";
import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-200 "
      >
        <CartProvider>
        <div className="fixed bg-white w-full ">
        <Header/>
        </div>
        <div className="pt-14 p-2">
        {children}
        </div>
        <div className="">
          <Footer/>
        </div>
        </CartProvider>
      </body>
    </html>
  );
}
